CREATE TABLE DATA_PROCESS (
    ID_DATA_PROCESS BIGSERIAL PRIMARY KEY,
    ID_DATA_INPUT BIGINT NOT NULL,
    ID_DATA_OUTPUT BIGINT NOT NULL,
    NM_PROCESS VARCHAR NOT NULL,
    DT_INCLUSION DATE NOT NULL
);
