ALTER TABLE PRODUCT_DATA
    ADD CONSTRAINT FK_PRODUCT_DATA_ID_PRODUCT_PRODUCT
    FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCT (ID_PRODUCT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE PRODUCT_DATA
    ADD CONSTRAINT FK_PRODUCT_DATA_ID_DATA_DATA
    FOREIGN KEY (ID_DATA)
    REFERENCES DATA (ID_DATA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
