CREATE SEQUENCE PRODUCT_ID_PRODUCT_SEQ;
ALTER SEQUENCE PRODUCT_ID_PRODUCT_SEQ OWNER TO ADMIN;
ALTER SEQUENCE PRODUCT_ID_PRODUCT_SEQ OWNED BY PRODUCT.ID_PRODUCT;

CREATE SEQUENCE DATA_ID_DATA_SEQ;
ALTER SEQUENCE DATA_ID_DATA_SEQ OWNER TO ADMIN;
ALTER SEQUENCE DATA_ID_DATA_SEQ OWNED BY DATA.ID_DATA;

CREATE SEQUENCE PRODUCT_DATA_ID_PRODUCT_DATA_SEQ;
ALTER SEQUENCE PRODUCT_DATA_ID_PRODUCT_DATA_SEQ OWNER TO ADMIN;
ALTER SEQUENCE PRODUCT_DATA_ID_PRODUCT_DATA_SEQ OWNED BY PRODUCT_DATA.ID_PRODUCT_DATA;
