ALTER TABLE DATA_PROCESS
    ADD CONSTRAINT FK_DATA_PROCESS_ID_DATA_INPUT_DATA
    FOREIGN KEY (ID_DATA_INPUT)
    REFERENCES DATA (ID_DATA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE DATA_PROCESS
    ADD CONSTRAINT FK_DATA_PROCESS_ID_DATA_OUTPUT_DATA
    FOREIGN KEY (ID_DATA_OUTPUT)
    REFERENCES DATA (ID_DATA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
