CREATE INDEX IDX_PRODUCT_DATA_ID_PRODUCT ON PRODUCT_DATA (ID_PRODUCT);
CREATE INDEX IDX_PRODUCT_DATA_ID_DATA ON PRODUCT_DATA (ID_DATA);
CREATE INDEX IDX_DATA_process_ID_DATA_INPUT ON DATA_PROCESS (ID_DATA_INPUT);
CREATE INDEX IDX_DATA_process_ID_DATA_OUTPUT ON DATA_PROCESS (ID_DATA_OUTPUT);
CREATE INDEX IDX_DPR_ID_DATA_process ON DATA_PROCESS_RESULT (ID_DATA_PROCESS);
CREATE INDEX IDX_DPR_ID_PRODUCT ON DATA_PROCESS_RESULT (ID_PRODUCT);
CREATE INDEX IDX_DPR_ID_DATA ON DATA_PROCESS_RESULT (ID_DATA);
