CREATE SEQUENCE PRODUCT_ID_PRODUCT_SEQ;
ALTER SEQUENCE PRODUCT_ID_PRODUCT_SEQ OWNER TO ADMIN;
ALTER SEQUENCE PRODUCT_ID_PRODUCT_SEQ OWNED BY PRODUCT.ID_PRODUCT;

CREATE SEQUENCE DATA_ID_DATA_SEQ;
ALTER SEQUENCE DATA_ID_DATA_SEQ OWNER TO ADMIN;
ALTER SEQUENCE DATA_ID_DATA_SEQ OWNED BY DATA.ID_DATA;

CREATE SEQUENCE DATA_PROCESS_ID_DATA_PROCESS_SEQ;
ALTER SEQUENCE DATA_PROCESS_ID_DATA_PROCESS_SEQ OWNER TO ADMIN;
ALTER SEQUENCE DATA_PROCESS_ID_DATA_PROCESS_SEQ OWNED BY DATA_PROCESS.ID_DATA_PROCESS;

CREATE SEQUENCE DATA_PROCESS_RESULT_ID_DATA_PROCESS_RESULT_SEQ;
ALTER SEQUENCE DATA_PROCESS_RESULT_ID_DATA_PROCESS_RESULT_SEQ OWNER TO ADMIN;
ALTER SEQUENCE DATA_PROCESS_RESULT_ID_DATA_PROCESS_RESULT_SEQ OWNED BY DATA_PROCESS_RESULT.ID_DATA_PROCESS_RESULT;

CREATE SEQUENCE PRODUCT_DATA_ID_PRODUCT_DATA_SEQ;
ALTER SEQUENCE PRODUCT_DATA_ID_PRODUCT_DATA_SEQ OWNER TO ADMIN;
ALTER SEQUENCE PRODUCT_DATA_ID_PRODUCT_DATA_SEQ OWNED BY PRODUCT_DATA.ID_PRODUCT_DATA;
