CREATE TABLE PRODUCT (
    ID_PRODUCT BIGSERIAL PRIMARY KEY,
    NM_PRODUCT VARCHAR NOT NULL,
    VL_PRODUCT DECIMAL NOT NULL
);

CREATE TABLE DATA (
    ID_DATA BIGSERIAL PRIMARY KEY,
    PATH_DATA UUID NOT NULL,
    TP_DATA VARCHAR NOT NULL,
    DT_INCLUSION DATE NOT NULL
);

CREATE TABLE PRODUCT_DATA (
    ID_PRODUCT_DATA BIGSERIAL PRIMARY KEY,
    ID_PRODUCT BIGINT NOT NULL,
    ID_DATA BIGINT NOT NULL
);

CREATE TABLE DATA_PROCESS (
    ID_DATA_PROCESS BIGSERIAL PRIMARY KEY,
    ID_DATA_INPUT BIGINT NOT NULL,
    ID_DATA_OUTPUT BIGINT NOT NULL,
    NM_PROCESS VARCHAR NOT NULL,
    DT_INCLUSION DATE NOT NULL
);

CREATE TABLE DATA_PROCESS_RESULTADO (
    ID_DATA_PROCESS_RESULTADO BIGSERIAL PRIMARY KEY,
    ID_DATA_PROCESS BIGINT NOT NULL,
    ID_DATA BIGINT NOT NULL,
    PC_TRUST DECIMAL NOT NULL,
    ID_PRODUCT BIGINT NOT NULL,
    IS_VALID BOOLEAN NOT NULL
);

-- ============================================================
-- Criação das chaves estrangeiras
-- ============================================================

-- PRODUCT_DATA
ALTER TABLE PRODUCT_DATA
    ADD CONSTRAINT FK_PRODUCT_DATA_ID_PRODUCT_PRODUCT
    FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCT (ID_PRODUCT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE PRODUCT_DATA
    ADD CONSTRAINT FK_PRODUCT_DATA_ID_DATA_DATA
    FOREIGN KEY (ID_DATA)
    REFERENCES DATA (ID_DATA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

-- DATA_PROCESS
ALTER TABLE DATA_PROCESS
    ADD CONSTRAINT FK_DATA_PROCESS_ID_DATA_INPUT_DATA
    FOREIGN KEY (ID_DATA_INPUT)
    REFERENCES DATA (ID_DATA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE DATA_PROCESS
    ADD CONSTRAINT FK_DATA_PROCESS_ID_DATA_OUTPUT_DATA
    FOREIGN KEY (ID_DATA_OUTPUT)
    REFERENCES DATA (ID_DATA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

-- DATA_PROCESS_RESULTADO
ALTER TABLE DATA_PROCESS_RESULTADO
    ADD CONSTRAINT FK_DATA_PROCESS_RESULTADO_ID_DATA_PROCESS_DATA_PROCESS
    FOREIGN KEY (ID_DATA_PROCESS)
    REFERENCES DATA_PROCESS (ID_DATA_PROCESS)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE DATA_PROCESS_RESULTADO
    ADD CONSTRAINT FK_DATA_PROCESS_RESULTADO_ID_DATA_DATA
    FOREIGN KEY (ID_DATA)
    REFERENCES DATA (ID_DATA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE DATA_PROCESS_RESULTADO
    ADD CONSTRAINT FK_DATA_PROCESS_RESULTADO_ID_PRODUCT_PRODUCT
    FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCT (ID_PRODUCT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

-- ============================================================
-- Índices adicionais
-- ============================================================
CREATE INDEX IDX_PRODUCT_DATA_ID_PRODUCT ON PRODUCT_DATA (ID_PRODUCT);
CREATE INDEX IDX_PRODUCT_DATA_ID_DATA ON PRODUCT_DATA (ID_DATA);
CREATE INDEX IDX_DATA_process_ID_DATA_INPUT ON DATA_PROCESS (ID_DATA_INPUT);
CREATE INDEX IDX_DATA_process_ID_DATA_OUTPUT ON DATA_PROCESS (ID_DATA_OUTPUT);
CREATE INDEX IDX_DPR_ID_DATA_process ON DATA_PROCESS_RESULTADO (ID_DATA_PROCESS);
CREATE INDEX IDX_DPR_ID_PRODUCT ON DATA_PROCESS_RESULTADO (ID_PRODUCT);
CREATE INDEX IDX_DPR_ID_DATA ON DATA_PROCESS_RESULTADO (ID_DATA);
