site_name: PDI - Unifor
site_author: Produtos de Mercado - PDI Unifor
site_url: https://unifor.br
site_description: Documentação PDI
repo_name: PDI
repo_url: https://github.com/EygonSaldanha/pdi-reconhecimento-produtos
#theme: readthedocs, windmill, dracula, material
theme: 
  name: material
  lang: pt

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
      puml_keyword: puml
      verify_ssl: true
      auto_dark: false

extra:
  favicon: ./favicon.ico